apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: development
type: Opaque
data:
    postgres-user: cG9zdGdyZXM=
    postgres-password: c3JkamFuMjM=
    postgres-db: YXV0aF9kYg==